---

- name: In-Memory inventory playbook
  hosts: workstation

  tasks:
  - name: Fetch Instance Info
#    os_server_info:
    os_server_facts:
      cloud: openstack
#      cloud: ospcloud
    register: result

  - name: Add host
    add_host:
      name: "{{ item.public_v4 }}"
      group: "{{ item.metadata.group }}"
#    with_items: "{{result.openstack_servers}}"
    with_items: "{{result.ansible_facts.openstack_servers}}"

  - name: Add host
    add_host:
      name: "{{ item.public_v4 }}"
      group: "{{ item.metadata.deployment_name }}"
#    with_items: "{{result.openstack_servers}}"
    with_items: "{{result.ansible_facts.openstack_servers}}"
